parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Services\Cart\CartInterface:
        alias: App\Services\Cart\CartHandler

    App\Services\Product\ProductServiceInterface:
        alias: App\Services\Product\ProductHandler
